version: '3.5'
services:
  jenkins:
    build: ./
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: on-failure
    environment:
      JAVA_OPTS: "-Xmx1024m"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /home/jenkins/jenkins:/var/jenkins_home